
import * as Yup from 'yup';

export const inicialGettingStartValues = {
    name:'',
    email:'',
    password:'',
    genre:'',
    birthday: "",
    country: "",
    city: "",
    mostTime: "",
    schoolLevel: "",
    job: "",
    relationship: "",
    children: "",
    joy: "",
    proportionJoy: "",
    lonely: "",
    sleep: "",
    wakeupTimes: "",
    lifeStatus: "",
    finance: "",
    satisfied: "",
    relationshipJoy: "",
    jobJoy: "",
    postponeGoals: "",
    anxious: "",
  }
  
export const GettingStartSchema = Yup.object().shape({
    email: Yup.string().email('Invalid email').required('Required'),
    password: Yup.string().required('Required'),
    name: Yup.string(),
    genre:Yup.string(),
    birthday: Yup.string(),
    country: Yup.string(),
    city: Yup.string(),
    mostTime: Yup.string(),
    schoolLevel: Yup.string(),
    job: Yup.string(),
    relationship: Yup.string(),
    children: Yup.string(),
    joy: Yup.string(),
    proportionJoy: Yup.string(),
    lonely: Yup.string(),
    sleep: Yup.string(),
    wakeupTimes: Yup.string(),
    lifeStatus: Yup.string(),
    finance: Yup.string(),
    satisfied: Yup.string(),
    relationshipJoy: Yup.string(),
    jobJoy: Yup.string(),
    postponeGoals: Yup.string(),
    anxious: Yup.string(),
  });
  